services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: hungnp25_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    networks:
      - hungnp25_network
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
  #   restart: always
  #   container_name: hungnp25_es
  #   environment:
  #     discovery.type: single-node
  #     xpack.security.enabled: "false"
  #     ES_JAVA_OPTS: -Xms512m -Xmx512m
  #   networks:
  #     - hungnp25_network
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   volumes:
  #     - ./data/elasticsearch:/usr/share/elasticsearch/data
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.11.4
  #   restart: always
  #   container_name: hungnp25_logstash
  #   environment:
  #     ES_JAVA_OPTS: -Xms512m -Xmx512m
  #     LS_PIPELINE_BATCH_SIZE: 500
  #     LS_PIPELINE_BATCH_DELAY: 300
  #   networks:
  #     - hungnp25_network
  #   ports:
  #     - "5044:5044"
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   depends_on:
  #     - elasticsearch
networks:
  hungnp25_network:
    driver: bridge