services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: hungnp25_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    networks:
      - hungnp25_network
    ports:
      - 5432:5432

  redis:
    image: redis:7
    restart: always
    container_name: hungnp25_redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - hungnp25_network
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    restart: always
    container_name: hungnp25_es
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      - hungnp25_network
    ports:
      - 9200:9200
      - 9300:9300

networks:
  hungnp25_network:
    driver: bridge