basePath: /
definitions:
  dto.APIResponse:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.ContainerUpdate:
    properties:
      status:
        allOf:
        - $ref: '#/definitions/entities.ContainerStatus'
        enum:
        - "ON"
        - "OFF"
    required:
    - status
    type: object
  dto.CreateRequest:
    properties:
      container_name:
        type: string
      image_name:
        type: string
    required:
    - container_name
    - image_name
    type: object
  dto.DeleteRequest:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/entities.UserRole'
      username:
        type: string
    required:
    - email
    - password
    - role
    - username
    type: object
  dto.UpdatePasswordRequest:
    properties:
      current_password:
        type: string
      new_password:
        type: string
    type: object
  dto.UpdateRoleRequest:
    properties:
      role:
        $ref: '#/definitions/entities.UserRole'
      user_id:
        type: string
    required:
    - role
    - user_id
    type: object
  dto.UpdateScopeRequest:
    properties:
      is_added:
        type: boolean
      scopes:
        items:
          type: string
        type: array
      user_id:
        type: string
    required:
    - scopes
    - user_id
    type: object
  entities.ContainerStatus:
    enum:
    - "ON"
    - "OFF"
    type: string
    x-enum-varnames:
    - ContainerOn
    - ContainerOff
  entities.UserRole:
    enum:
    - manager
    - developer
    type: string
    x-enum-varnames:
    - Manager
    - Developer
host: localhost:8080
info:
  contact: {}
  description: Container Management System API
  title: VCS SMS API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login and receive JWT token
      parameters:
      - description: User login credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      summary: Login with username and password
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh the access token for the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: Access token refreshed successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Refresh access token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a user and return a JWT token
      parameters:
      - description: User registration request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      summary: Register a new user
      tags:
      - auth
  /auth/update/password:
    put:
      consumes:
      - application/json
      description: Update the password of the currently authenticated user
      parameters:
      - description: New password request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password updated successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Update own password
      tags:
      - auth
  /containers/create:
    post:
      consumes:
      - application/json
      description: Create a container with name and image
      parameters:
      - description: Container creation request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Container created successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Create a new container
      tags:
      - containers
  /containers/delete/{id}:
    delete:
      description: Delete a container by its ID
      parameters:
      - description: Container ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Container deleted successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Delete a container
      tags:
      - containers
  /containers/export:
    get:
      description: Export containers with optional filters and sorting to an Excel
        file
      parameters:
      - default: 1
        description: From index (default 1)
        in: query
        name: from
        type: integer
      - default: -1
        description: To index (default -1 for all)
        in: query
        name: to
        type: integer
      - description: Filter by ContainerId
        in: query
        name: container_id
        type: string
      - description: Filter by ContainerName
        in: query
        name: container_name
        type: string
      - description: Filter by Status
        enum:
        - "ON"
        - "OFF"
        in: query
        name: status
        type: string
      - description: Filter by IPv4
        in: query
        name: ipv4
        type: string
      - description: Sort by field
        enum:
        - container_id
        - container_name
        - status
        - ipv4
        - created_at
        - updated_at
        in: query
        name: field
        required: true
        type: string
      - description: Sort order
        enum:
        - asc
        - desc
        in: query
        name: order
        required: true
        type: string
      produces:
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      responses:
        "200":
          description: Excel file containing container data
          schema:
            type: file
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Export containers to Excel
      tags:
      - containers
  /containers/import:
    post:
      consumes:
      - multipart/form-data
      description: Import containers using an Excel (.xlsx) file
      parameters:
      - description: Excel file containing container data
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Import result with success and failure counts
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Import containers from Excel
      tags:
      - containers
  /containers/update/{id}:
    put:
      consumes:
      - application/json
      description: Update container information by container ID
      parameters:
      - description: Container ID
        in: path
        name: id
        required: true
        type: string
      - description: Container update payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ContainerUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Container updated successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Update a container
      tags:
      - containers
  /containers/view:
    get:
      description: Retrieve a list of containers with optional pagination, filtering,
        and sorting
      parameters:
      - default: 1
        description: From index (default 1)
        in: query
        name: from
        type: integer
      - default: -1
        description: To index (default -1 for all)
        in: query
        name: to
        type: integer
      - description: Filter by ContainerId
        in: query
        name: container_id
        type: string
      - description: Filter by ContainerName
        in: query
        name: container_name
        type: string
      - description: Filter by Status
        enum:
        - "ON"
        - "OFF"
        in: query
        name: status
        type: string
      - description: Filter by IPv4
        in: query
        name: ipv4
        type: string
      - description: Sort by field
        enum:
        - container_id
        - container_name
        - status
        - ipv4
        - created_at
        - updated_at
        in: query
        name: field
        required: true
        type: string
      - description: Sort order
        enum:
        - asc
        - desc
        in: query
        name: order
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with container list
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: View containers
      tags:
      - containers
  /report/mail:
    get:
      description: Generates a container uptime/downtime report and sends it to the
        provided email address
      parameters:
      - description: Recipient email address
        in: query
        name: email
        required: true
        type: string
      - description: Start date (e.g. 2006-01-02)
        in: query
        name: start_time
        required: true
        type: string
      - description: End date (defaults to current time)
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Report emailed successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Invalid input or time range
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Failed to retrieve data or send email
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Send container status report via email
      tags:
      - Report
  /users/delete:
    delete:
      consumes:
      - application/json
      description: Remove a user from the system (admin only)
      parameters:
      - description: User ID to delete
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User deleted successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Delete a user
      tags:
      - users
  /users/update/role:
    put:
      consumes:
      - application/json
      description: Update role of a user (admin only)
      parameters:
      - description: User ID and new role
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Role updated successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Update a user's role
      tags:
      - users
  /users/update/scope:
    put:
      consumes:
      - application/json
      description: Update permission scope of a user (admin only)
      parameters:
      - description: User ID, scopes, and whether to add or remove
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateScopeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Scope updated successfully
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.APIResponse'
      security:
      - BearerAuth: []
      summary: Update a user's scope
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
